config/routes.rb
Workspace::Application.routes.draw do
  get 'news/news'
  match '/signup',  to: 'users#new',via: 'get'
  resources :users
  get 'sales/index'
  resources :comments
  match '/about', to: 'static_pages#about', via: 'get'
  get 'static_pages/help'
  get 'static_pages/myra'
  get 'static_pages/serrata'
  get 'static_pages/hakea_blossom'
  get 'static_pages/stingray'
  get 'static_pages/l_90'
  get 'static_pages/wallabies'
  get 'static_pages/palm_beach_wharf'
  get 'static_pages/bennets'
  get 'static_pages/bonnie_doon'
  get 'static_pages/the_basin'
  get 'static_pages/great_mackerel'
  get 'static_pages/lion_island'
  
  get "home/index"
root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :password, length: { minimum: 6 }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def news
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def help
  end
  
  def myra
  end
  
  def serrata
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Myra Club!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Myra"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% provide(:title, 'Comments') %>
<h1>Visitor comments</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Remove', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<table>
    <tr>
        <div class="fadein">
        <td><%= image_tag 'myra4-32c_icon_1_xxxhdpi.png', :alt => 'Myra Logo', :class => 'img-circle' %></td>
        </div>
        <td>
            <h1>Myra</h1>
            <p>Welcome to Myra the Ferryboat's page.
        </td>        
    </tr>
</table>
<img>

app/views/news/news.html.erb
<% provide(:title, 'News') %>
<h1>Recent News</h1>
<p>Currently the book is on its second draft edition.</p>
<%= link_to "Sign up now for updates!", signup_path, class: "btn btn-large btn-primary" %>

app/views/sales/index.html.erb
<% provide(:title, 'Sales') %>
<h1>Sales</h1>

<p>There are two ways to order Myra the Ferryboat, and three kinds of books.</p>
<ul>
<li>Softcover AUD $15.00</li>
<li>Hardcover with Dust Jacket AUD $25.00</li>
<li>Hardcover ImageWrap (more durable for children) also AUD $25.00</li>
</ul>
<h3>In Sydney</h3>
<p>Local sales in Sydney and the Northern Beaches can be handled by the auther.</p>
<p>355/6 Cowper Wharf Roadway, Woolloomooloo, NSW, Australia, 2011.</p>
<p>Phone: 0435 499 052</p>
<p>E-mail: timofeyc at hotmail.com</p>
<hr>

<h3>Northern Beaches</h3>
<p>Call to check for availability of copies close to Palm Beach.</p>
<p>Mobile: 048 845 6745</p>
<p>
<p>Postage within Australia is AUD $3.75 per book.
<hr>

<h3>Online</h3>
<p>Orders can also be placed from the publisher.</p>
<p>Please note, the contrast is too high on the current issue and is in the process of being re-worked.</p>
<p>You should order from the above sources until this has been completed.</p>
<a href="http://blur.by/1tPZ4iS">Myra sales online.</a></a>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<%= image_tag "characters/The-Author-1-350.png" %>
<p>
  The author and illustrator of this book is also an artist, a teacher and a programmer.
He was born in North Sydney but was raised in Silicon Valley.  
As well as a history making virtual reality games and work in the as fine arts, he has lived in South Korea and and been through a series of start up companies.
Now, between contracts as an mobile applications developer and programmer, he finds the time to draw and make stories.
While staying at Coaster Retreat in 2014 for a period of a month, Myra told him her story on frequewnt trips back and forth across Pittwater.
</p>

app/views/static_pages/bennets.html.erb
<% provide(:title, 'Bennetts') %>
<h1>Bennetts Wharf</h1>
<p>
  The first stop on Myra's route.  Bennetts along with Bonnie Doon wharf are the only two stops at Coasters Retreat.
</p>
<div class="fadein">
<%= image_tag "places/Bennetts-0-350.png" %>
</div>

app/views/static_pages/bonnie_doon.html.erb
<% provide(:title, 'Bonnie Doon') %>
<h1>Bonnie Doon Wharf</h1>
<p>
The second stop on Myra's route.  
The Bonnie Doon wharf is the oldest of two wharves at Coasters Retreat which has no road or land access and is entirely dependent on Myra and the Palm Beach Ferry Service.
The area was first inhabited by Indigenous Australians, the Kuringgai, so the area became the Ku-Ring-Gai Chase National Park. 
On October 5th, 2014, an anniversary celebration was held and Bonnie Doon Day was born.</p>
<div class="fadein">
<%= image_tag 'places/Bonnie-Doon-1-350.png', :alt => 'Drawing of Bonnie Doon', :class => 'img-circle' %>
</div>

app/views/static_pages/great_mackerel.html.erb
<% provide(:title, 'Great Makerel') %>
<h1>Great Makerel Beach</h1>
<p>
  The last stop on Myra's route.
</p>

app/views/static_pages/hakea_blossom.html.erb
<% provide(:title, 'Hakea Blossom') %>

<table>
    <tr><td>
        <table><tr><td><h1>Hakea Blossom</h1></td></tr>
        <tr><td>The friend of Myra.<td></tr>
        <tr>
            <div class="fadein">
            <td><%= image_tag "characters/Hakea-adnata-0-360.png" %></td></tr>
            </div>
        </table>
    </td>
    <td>
        <table>
            <tr><td>
Hakea is a type of shrubs or small trees from to Australia. 
They grow around the country, but most are found in Western Australia.
Hakeas are named after Baron Christian Ludwig von Hake, the 18th century German patron of botany, following Heinrich Schrader's description of Hakea teretifolia in 1797.
Grevilleas are similar to Hakea and it's difficult sometimes to tell the difference.
The Hakea baby blossom from the story is called Hakea francisiana (also called an Emu Tree).
This plant takes it name from George Francis, a Director of the Adelaide Botanic Gardens and distant relative of the author.
</br>
Pictured: Hakea adnata, Southern WA.
            </td></tr>
        </table>
        </td></tr>
</table>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is the help page for Myra the Ferryboat
</p>

app/views/static_pages/l_90.html.erb
<% provide(:title, 'L-90') %>
<h1>The L-90 Bus</h1>
<p>
  One of Myra's friends.
</p>

app/views/static_pages/lion_island.html.erb
<% provide(:title, 'Lion Island') %>
<div class="fadein">
<table>
    <tr><td>
        <table>
            <tr><td><h1>Lion Island</h1>
            </h1></td></tr>
            <tr><td>Lion Island.<td></tr>
            <div id="image" class="hide">
            <tr><td>
                <%= image_tag "places/lion-island-1-350.png" %>
            </div>
        </table>
    </td>
    <td>
&nbsp;&nbsp;Lion Island is located at the mouth to the Hawkesbury River inside Broken Bay, in New South Wales, Australia.
It was originally named Mount Elliott Island by Governor Arthur Phillip in 1789, because it resembled Gibraltar where his friend, General Elliott, won battles against his foes.     
In 1956, the Lion Island Fauna Reserve was establishedand.  
In 1977 it was renamed the Lion Island Nature Reserve        
    </td></tr>
</table>
</div>

app/views/static_pages/myra.html.erb
<% provide(:title, 'Myra') %>
<table>
    <tr><td>
        <table>
            <tr><td><h1>Myra</h1></td></tr>
            <tr><td>The main character of the story.<td></tr>
            <tr>
                <div class="fadein">
                <td><%= image_tag "characters/Myra-Character-d1-0b-350.png" %>
                </div>
        </table>
    </td>
    <td>
Myra is Norman Wright River Ferry that measures 15 metrs.  
Built in 1985 she is charming and knowledgeable.
She has a top deck which gives passengers a wonderful view of Broken Bay.
    </td></tr>
</table>

app/views/static_pages/palm_beach_wharf.html.erb
<% provide(:title, 'Palm Beach Wharf') %>
<table>
    <tr><td>
        <table><tr><td><h1>The Palm Beach Wharf</h1></td></tr>
        <tr><td>The beginning of Myra's route.<td></tr>
        <tr><td>
            <div class="fadein">
            <%= image_tag "places/Palm-Beach-Wharf-0-350.png" %>
            </div>
        </td></tr>
        </table>
    </td>
    <td>
        <table>
        <tr><td>
        The Palm Beach Ferry runs a service from the wharf to Ettalong, Great Mackerel Beach, Currawong Beach, Coasters Retreat and The Basin.    
        </td></tr>
        </table>
        </td></tr>
</table>

app/views/static_pages/serrata.html.erb
<% provide(:title, 'Serrata') %>
<table>
    <tr><td>
        <table><tr><td><h1>The Serrata</h1></td></tr>
        <tr><td>The nemisis of Myra (not really!)<td></tr>
        <tr><td>
            <div class="fadein">
            <%= image_tag "characters/Serrata2a_320_xxhdpi.png" %>
            </div>
        </td></tr>
        </table>
    </td>
    <td>
        <table>
            <tr>
            <div class="fadein">
                <td><%= image_tag("characters/Banksia-serrata-0-252.png", :align=> "middle") %></td>
            <tr><td>The Serrata character is based on the Banksia serrata tree, also known as old man banksia or saw banksia.  
            Native to the east coast of Australia, it has serrated leaves and large yellow flower spikes.
            It grows exclusively in sandy soils, and is usually the dominant plant in scrubland.            
            The fire-retardant bark is thick and often black from past bushfires. It oozes red sap when injured. 
            The tree has a lignotuber, which is an underground structure that stores energy used to grow back after a bushfire. 
            </td></tr>
        </table>
        </td></tr>
</table>

app/views/static_pages/stingray.html.erb
<% provide(:title, 'Stingray') %>
<h1>The Stingray</h1>
<p>
  The Stingray is lots of fun!
</p>
  <div class="fadein">
  <%= image_tag "characters/Common-stingaree-0-350.png" %>
  </div>
<table><tr><td>The Stingray character is based on the common stingaree, a species commonly found in inshore waters off eastern Australia.
    The tail measures 86–90% as long as the disc and has one or two serrated stinging spines on top the tail about halfway along its length.
    It is on this stinger that a loop at the end of a rope can be hooked.  The Hakea blossoms can then catch a ride like a banana boat on the tail of The Stingaree.
    This is why it had such a long long tail in the story!
</td></tr></table>

app/views/static_pages/the_basin.html.erb
<% provide(:title, 'The Basin') %>
<h1>The Basin</h1>
<p>
  The fourth stop on Myra's route.
</p>

app/views/static_pages/wallabies.html.erb
<% provide(:title, 'Wallabies') %>
<h1>Wallabies</h1>
<p>
  Wallabies at Coasters.
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up to receive updates!</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>